version: '3'

services:

  db-master:
    image: ${DB}:latest
    environment:
      - MYSQL_ROOT_PASSWORD=toor
    volumes:
      - sql-data-master:/var/lib/mysql
      - ./config/mysql/master:/tmp/mwdd
    entrypoint: "/tmp/mwdd/entrypoint.sh"
    command: "mysqld"

  db-slave:
    image: ${DB}:latest
    environment:
      - MYSQL_ROOT_PASSWORD=toor
    volumes:
      - sql-data-slave:/var/lib/mysql
      - ./config/mysql/slave:/tmp/mwdd
    entrypoint: "/tmp/mwdd/entrypoint.sh"
    command: "mysqld"

  db-configure:
    image: ${DB}:latest
    environment:
      - "MYSQL_SLAVE_PASSWORD=toor"
      - "MYSQL_MASTER_PASSWORD=toor"
      - "MYSQL_ROOT_PASSWORD=toor"
      - "MYSQL_REPLICATION_USER=repl"
      - "MYSQL_REPLICATION_PASSWORD=repl"
    depends_on:
     - db-master
     - db-slave
    volumes:
      - ./scripts/mysql_connector.sh:/tmp/mysql_connector.sh
      - ./scripts/wait-for-it.sh:/tmp/wait-for-it.sh
    command: /bin/bash -x /tmp/mysql_connector.sh

  web :
    image: webdevops/${PHPORHHVM}-${WEBSERVER}${DOCKERPHPDEV}:${RUNTIMEVERSION}
    environment:
     # Used by various maintenance scripts to find MediaWiki.
     # Also required for /var/www/index.php - https://phabricator.wikimedia.org/T153882
     - VIRTUAL_HOST=*.web.mw.localhost
     - PHP_DEBUGGER=xdebug
     - XDEBUG_REMOTE_AUTOSTART=1
     - XDEBUG_REMOTE_HOST=${IDELOCALHOST}
     - XDEBUG_REMOTE_PORT=9000
     - XDEBUG_REMOTE_CONNECT_BACK=1
     - XDEBUG_CONFIG="idekey=xdbg"
     - XDEBUG_REMOTE_MODE=req
     - PHP_IDE_CONFIG=serverName=docker
    depends_on:
     - db-configure
    volumes:
     - "${DOCKER_MW_REPO_PATH}:/var/www/repo"
     - ./config/httpd/vhost/repo.conf:/opt/docker/etc/httpd/conf.d/repo.conf:ro
     - "${DOCKER_MW_CLIENT_PATH}:/var/www/client"
     - ./config/httpd/vhost/client.conf:/opt/docker/etc/httpd/conf.d/client.conf:ro
     - ./config/mediawiki:/var/www/repo/.docker:ro
     - ./config/mediawiki:/var/www/client/.docker:ro
     - ./config/hhvm/php.ini:/etc/hhvm/php.ini:ro
     - ./config/hhvm/server.ini:/etc/hhvm/server.ini:ro
     - ./scripts/wait-for-it.sh:/srv/wait-for-it.sh:ro
     - mw-images:/var/www/images/dockerdp

  nginx-proxy:
    image: jwilder/nginx-proxy
    environment:
      - VIRTUAL_HOST=proxy.mw.localhost
    ports:
      - "${DOCKER_MW_PORT}:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

volumes:
  sql-data-master:
  sql-data-slave:
  mw-images:
